spring:
  application:
    name: Spring_Ai_Prac

  profiles:
    include: secret

  ai:
    openai:
      chat:
        options:
          model: llama-3.1-8b-instant
          temperature: 0.7
#          max-tokens: 15